cb-208 create `<UnfulfilledRequirements />` component
selsa-inube/portal-crm pull request #2
Opened 2024-09-23 20:25 UTC by Andresbl123

Implementar el componente UnfulfilledRequirements

![image](https://github.com/user-attachments/assets/fc745b59-a65b-4c49-b40e-9efc907e0c5e)

2024-09-24 14:39 UTC, novadeveloper14 requested changes

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/cards/UnfulfilledRequirements/UnfulfilledRequirements.stories.tsx
the story should be a folder called stories

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/cards/UnfulfilledRequirements/UnfulfilledRequirements.stories.tsx
> +  argTypes: {
This information must be obtained from a file called props.ts

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/cards/UnfulfilledRequirements/index.tsx
> +import { Fieldset } from "@src/components/data/Fieldset";
use the `@components` alias directly

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/data/Fieldset/Fieldset.stories.tsx
the story should be a folder called stories

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/data/Fieldset/Fieldset.stories.tsx
> +  argTypes: {
This information must be obtained from a file called props.ts in the stories folder

2024-09-24 14:39 UTC, novadeveloper14 commented on src/components/data/Fieldset/index.tsx
> +import { StyledContainerFieldset } from "./styles";
organize imports

2024-09-25 16:03 UTC, Andresbl123 commented on src/components/cards/UnfulfilledRequirements/index.tsx
> +import { Fieldset } from "@src/components/data/Fieldset";
resuelto

2024-09-25 16:04 UTC, Andresbl123 commented on src/components/data/Fieldset/index.tsx
> +import { StyledContainerFieldset } from "./styles";
resuelto

2024-09-27 06:06 UTC, novadeveloper14 approved these changes

2024-09-27 20:18 UTC, carin91 approved these changes

2024-09-27 20:18 UTC, merged